language: python
python:
  - 2.7
  
notifications:
  email: false
  slack: slac-suncat:uMRwgQgYaSJFNr48PlZ1vtuf

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose
  - pip install mpmath
  - pip install python-ase
  - python setup.py install #install catmap
 
# Run tests; this is a very crude way of testing things
# We should move to a more elegant strategy in the future
script:
  - python test_dependencies.py
  - cd tutorials/1-generating_input_file
  - python generate_input.py
  - cd ../2-creating_microkinetic_model
  - python mkm_job.py
  - cd ../3-refining_microkinetic_model
  - python mkm_job.py
  - cd ../thermodynamic_descriptors
  - python mkm_job.py
  - cd ../electrochemistry/HER
  - python mkm_job.py
  - cd ../ORR_scaling
  - python make_input.py
  - python mkm_job.py
  - cd ../ORR_thermo
  - python make_input.py
  - python mkm_job.py
